##### Calculate voronoi statistics #####
#
# This modifier function generates a histogram of the Voronoi motifs generated by the 
# [Voronoi analysis modifier](manual:modifiers.voronoi_analysis) sorted by occurence.

from ovito.data import DataCollection, ParticleType, DataTable, ElementType
from ovito.pipeline import ModifierInterface
import numpy as np
from traits.api import Bool, Int, ListFloat


class CalculateVoronoiStatistics(ModifierInterface):
    n_start = Int(2, label="N_start")
    n_end =  Int(2, label="N_end") 
    max_indices = Int(10, label="Max indices")  
    rel_mode = Bool(True, label="Relative mode")

    # This helper function takes a two-dimensional array and computes a frequency
    # histogram of the data rows using some NumPy magic.
    # It returns two arrays (of equal length):
    #    1. The list of unique data rows from the input array
    #    2. The number of occurences of each unique row
    # Both arrays are sorted in descending order such that the most frequent rows
    # are listed first.

    def voro_format(voro_index, i_start, i_end):
        s = "⟨"
        for el in voro_index[i_start:i_end]:
            s += f"{el}, "
        s += f"{voro_index[i_end]}⟩"    
        return s
        
    def voro_format_label(i_start, i_end):
        s = "⟨"
        for i in range(i_start,i_end):
            s += f"n{i}, "
        s += f"n{i_end}⟩"    
        return s                
            
    def row_histogram(a):
        ca = np.ascontiguousarray(a).view([('', a.dtype)] * a.shape[1])
        unique, indices, inverse = np.unique(ca, return_index=True, return_inverse=True)
        counts = np.bincount(inverse)
        sort_indices = np.argsort(counts)[::-1]
        return (a[indices[sort_indices]], counts[sort_indices])

    def modify(self, data: DataCollection, frame: int, **kwargs):

        # Access computed Voronoi indices.
        # This is an (N) x (M) array, where M is the maximum face order.
        if "Voronoi Index" not in data.particles.keys():
            print("############")
            print( "Please generate Voronoi Indices first. \n 1) Add a Voronoi Analysis Modifier to your pipeline. \n 2) Activate the option Compute Voronoi indices.")
            print("############")
            exit
        
        if self.n_end >= data.attributes["Voronoi.max_face_order"]:       
            self.n_end = data.attributes["Voronoi.max_face_order"]-1
            
        voro_indices = data.particles['Voronoi Index']
        if self.max_indices >= len(voro_indices):
            self.max_indices = len(voro_indices)
        
        # Compute frequency histogram.
        unique_indices, counts = self.row_histogram(voro_indices)
        assert self.max_indices < len(unique_indices),f"Max number of unique indices is {len(unique_indices)} not {self.max_indices}"
                                    
        table = DataTable(title=f'Voronoi statistics of the {self.max_indices} most frequenct motifs', plot_mode=DataTable.PlotMode.BarChart)
        
        table.x = table.create_property(f'Voronoi index {self.voro_format_label(self.n_start, self.n_end)}', data=np.arange(0, self.max_indices, 1, dtype=int))
        
        for i in np.arange(0, self.max_indices, 1, dtype=int):
            table.x.types.append(ElementType(id=i, name=self.voro_format(unique_indices[i], self.n_start, self.n_end)))
    
        if self.rel_mode:
            table.y = table.create_property('Frequeancy in %', data=counts[:self.max_indices]/len(voro_indices)*100, dtype=float)
        else:
            table.y = table.create_property('Count', data=counts[:self.max_indices])
        data.objects.append(table)
        
    